### ISSUE TITLE
Baselines: finetuning

### ISSUE THREAD

**Issue by onurgu** [boun-tabi-LMG/turkish-lm-tuner#16]
There are missing baseline results for some tasks/models we want to compare our models with. Potential baselines could be BERTurk, mBERT, mT5, or mBART, depending on whether the task type is classification or conditional generation. We should also consider the model size when choosing a baseline for a fair comparison. Our model has 1.1 billion parameters.

**Comment by gokceuludogan** [comment]
Outdated.
