### ISSUE TITLE
Setting GitHub Workflows

### ISSUE THREAD

**Issue by gokceuludogan** [boun-tabi-LMG/turkish-lm-tuner#47]
Setting GitHub Workflows for packages & documentation release.

**Comment by furkanakkurt1335** [comment]
Deploying to GitHub Pages works now with `doc.yml`. As the `docs` in `main` is updated, the live website will be updated also at [boun-tabi-lmg.github.io/turkish-lm-tuner](https://boun-tabi-lmg.github.io/turkish-lm-tuner/index.html).

**Comment by furkanakkurt1335** [comment]
The package workflow is also working, the first release is [here](https://pypi.org/project/turkish-lm-tuner/1/).

**Comment by furkanakkurt1335** [comment]
We can close the issue if approved. I tested both workflows.

**Comment by gokceuludogan** [comment]
Great work!
